name: azr_env
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytorch-cpu
  - numpy>=1.24.0
  - tqdm>=4.65.0
  - psutil>=5.9.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - pip:
    - transformers>=4.30.0
    - datasets>=2.12.0
    - accelerate>=0.20.0
    - wandb>=0.15.0
